### ISSUE TITLE
Go lint fixes

### ISSUE THREAD

**Issue by ashfame** [Automattic/neurobot#4]
Go lint suggestions are not active in VSC, so need to enable that and attend to issues reported - https://goreportcard.com/report/github.com/automattic/matrix-workflow-builder

**Comment by psrpinto** [comment]
@ashfame Do you think this issue is still relevant. We also have https://github.com/Automattic/neurobot/issues/48

**Comment by ashfame** [comment]
@psrpinto Yep! This is for fixing our code so that locally go lint doesn't have any complaints. The other one is about setting the same checks on Github actions.

**Comment by psrpinto** [comment]
Ok, if I understand correctly, this one is about fixing the linting issues that the linting tool we setup in #48 found. If so, I think we could close this one and add an extra step in #48 (e.g. Fix linting issues). I think that would make sense since fixing linting issues will be a requirement for being able to close #48, as we won't be able to enforce a CI check without first fixing the existing issues.

**Comment by ashfame** [comment]
Sure! I am fine either way.

**Comment by psrpinto** [comment]
Ok, I add an extra "Fix all issues found by the linter" task in #48.
